language: node_js
sudo: required
services:
- docker
notifications:
  email: true
before_script:
- cd app
script:
- docker build -t travelrepublic/presentation-docker-node .
after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push travelrepublic/presentation-docker-node
